# Generated by Django 4.2 on 2025-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_join_time_user_joined_time_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adminuser',
            field=models.BooleanField(default=False),
        ),
    ]
