# Generated by Django 4.2 on 2025-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='None', max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=48),
        ),
    ]
