# Generated by Django 5.2 on 2025-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='WithOUtUsernName', max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='WithOUtName', max_length=48),
        ),
    ]
