# Generated by Django 4.2 on 2025-08-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
