# Generated by Django 4.2 on 2025-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='Losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
