# Generated by Django 4.2 on 2025-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_losses_score_losses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
