# Generated by Django 4.2 on 2025-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_score_games_alter_score_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizedText',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=256)),
                ('lang_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.AddField(
            model_name='game',
            name='mid',
            field=models.CharField(default='t', max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('player_1', 'player_1'), ('player_2', 'player_2'), ('draw', 'draw')], max_length=10),
        ),
    ]
