# Generated by Django 4.2 on 2025-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_localizedtext_delete_command_game_mid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedtext',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localizedtext',
            name='key',
            field=models.CharField(max_length=48),
        ),
    ]
