# Generated by Django 4.2 on 2025-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_localizedtext_id_alter_localizedtext_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedtext',
            name='key',
            field=models.IntegerField(),
        ),
    ]
