# Generated by Django 4.2 on 2025-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_game_played_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game_type',
            field=models.IntegerField(default=1),
        ),
    ]
