# Generated by Django 4.2 on 2025-08-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_score_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('joined_memebers', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
