# Generated by Django 4.2 on 2025-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sponser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang_code',
            field=models.CharField(default='fa', max_length=2),
        ),
    ]
