# Generated by Django 4.2 on 2025-08-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_sponser_id_alter_user_lang_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalizedText',
        ),
    ]
