version: '3.8'

services:

  db:
    image: postgres:17.5-alpine3.22
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env.dev


  django:
    build: .
    command: ["django"]
    volumes:
      - static_volume:/bot/src/static
      - media_volume:/bot/src/media
    expose:
      - 8000
    env_file:
      - ./src/.env.dev
    depends_on:
      - db

  nginx:
    build: ./src/nginx
    volumes:
      - static_volume:/bot/src/static
      - media_volume:/bot/src/media
      - ./src/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django

  bot:
    build: .
    command: ["bot"]
    volumes:
      - .:/bot
    env_file:
      - ./src/.env.dev
    depends_on:
      - db
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:


