# Generated by Django 4.2 on 2025-08-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adminuser',
        ),
    ]
