# Generated by Django 4.2 on 2025-08-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_score_losses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='Losses',
            new_name='losses',
        ),
    ]
