# Generated by Django 4.2 on 2025-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_localizedtext_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedtext',
            name='lang_code',
            field=models.CharField(default='fa', max_length=2),
        ),
    ]
