# Generated by Django 4.2 on 2025-08-17 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_localizedtext_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lang_code',
            field=models.CharField(default=2005, max_length=2),
            preserve_default=False,
        ),
    ]
