# Generated by Django 4.2 on 2025-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_game_played_time_user_lang_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
