name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    uses: kioteam-ir/kio-github-actions/.github/workflows/python-poetry-ci.yml@feat/organization-ci-workflows
    with:
      python-version: "3.13"
      lint-command: poetry run ruff check bot/ api/ tests/ tools/
      pre-test-command: poetry run poe compile
      test-command: poetry run pytest tests/ -v --tb=short
