name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master

concurrency:
  group: deploy-master
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /srv/kio/projects/4fall-bot

          git fetch origin
          git reset --hard origin/master

          docker compose pull
          docker compose up -d --build