name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-master
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /srv/kio/projects/4fall-bot

          git fetch origin
          git reset --hard origin/master

          docker compose pull
          docker compose up -d --build