name: Notify CI Result

on:
  workflow_run:
    workflows: ["CI", "Deploy"]
    types:
      - completed

concurrency:
  group: notify-ci-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:
  notify:
    uses: kioteam-ir/kio-github-actions/.github/workflows/notify-ci.yml@v1
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
