name: Notify Push

on:
  push:

jobs:
  notify:
    name: telegram notify
    if: github.event.deleted == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          disable_notification: true
          message: |
            🆕 New push to ${{ github.repository }}
            By: ${{ github.actor }}
            Ref: ${{ github.ref_name }}
            Message: ${{ github.event.head_commit.message }}
            ${{ github.event.head_commit.url }}